#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum OpCode {
    Blank = 0,
    Copy = 1,
    Load = 2,
    Store = 3,
    Branch = 4,
    Cbranch = 5,
    Branchind = 6,
    Call = 7,
    Callind = 8,
    Callother = 9,
    Return = 10,
    IntEqual = 11,
    IntNotequal = 12,
    IntSless = 13,
    IntSlessequal = 14,
    IntLess = 15,
    IntLessequal = 16,
    IntZext = 17,
    IntSext = 18,
    IntAdd = 19,
    IntSub = 20,
    IntCarry = 21,
    IntScarry = 22,
    IntSborrow = 23,
    Int2comp = 24,
    IntNegate = 25,
    IntXor = 26,
    IntAnd = 27,
    IntOr = 28,
    IntLeft = 29,
    IntRight = 30,
    IntSright = 31,
    IntMult = 32,
    IntDiv = 33,
    IntSdiv = 34,
    IntRem = 35,
    IntSrem = 36,
    BoolNegate = 37,
    BoolXor = 38,
    BoolAnd = 39,
    BoolOr = 40,
    FloatEqual = 41,
    FloatNotequal = 42,
    FloatLess = 43,
    FloatLessequal = 44,
    Unused1 = 45,
    FloatNan = 46,
    FloatAdd = 47,
    FloatDiv = 48,
    FloatMult = 49,
    FloatSub = 50,
    FloatNeg = 51,
    FloatAbs = 52,
    FloatSqrt = 53,
    FloatInt2float = 54,
    FloatFloat2float = 55,
    FloatTrunc = 56,
    FloatCeil = 57,
    FloatFloor = 58,
    FloatRound = 59,
    Multiequal = 60,
    Indirect = 61,
    Piece = 62,
    Subpiece = 63,
    Cast = 64,
    Ptradd = 65,
    Ptrsub = 66,
    Segmentop = 67,
    Cpoolref = 68,
    New = 69,
    Insert = 70,
    Zpull = 71,
    Popcount = 72,
    Lzcount = 73,
    Spull = 74,
    Max = 75,
}

const OPCODE_TABLE: [OpCode; 76] = [
    OpCode::Blank,
    OpCode::Copy,
    OpCode::Load,
    OpCode::Store,
    OpCode::Branch,
    OpCode::Cbranch,
    OpCode::Branchind,
    OpCode::Call,
    OpCode::Callind,
    OpCode::Callother,
    OpCode::Return,
    OpCode::IntEqual,
    OpCode::IntNotequal,
    OpCode::IntSless,
    OpCode::IntSlessequal,
    OpCode::IntLess,
    OpCode::IntLessequal,
    OpCode::IntZext,
    OpCode::IntSext,
    OpCode::IntAdd,
    OpCode::IntSub,
    OpCode::IntCarry,
    OpCode::IntScarry,
    OpCode::IntSborrow,
    OpCode::Int2comp,
    OpCode::IntNegate,
    OpCode::IntXor,
    OpCode::IntAnd,
    OpCode::IntOr,
    OpCode::IntLeft,
    OpCode::IntRight,
    OpCode::IntSright,
    OpCode::IntMult,
    OpCode::IntDiv,
    OpCode::IntSdiv,
    OpCode::IntRem,
    OpCode::IntSrem,
    OpCode::BoolNegate,
    OpCode::BoolXor,
    OpCode::BoolAnd,
    OpCode::BoolOr,
    OpCode::FloatEqual,
    OpCode::FloatNotequal,
    OpCode::FloatLess,
    OpCode::FloatLessequal,
    OpCode::Unused1,
    OpCode::FloatNan,
    OpCode::FloatAdd,
    OpCode::FloatDiv,
    OpCode::FloatMult,
    OpCode::FloatSub,
    OpCode::FloatNeg,
    OpCode::FloatAbs,
    OpCode::FloatSqrt,
    OpCode::FloatInt2float,
    OpCode::FloatFloat2float,
    OpCode::FloatTrunc,
    OpCode::FloatCeil,
    OpCode::FloatFloor,
    OpCode::FloatRound,
    OpCode::Multiequal,
    OpCode::Indirect,
    OpCode::Piece,
    OpCode::Subpiece,
    OpCode::Cast,
    OpCode::Ptradd,
    OpCode::Ptrsub,
    OpCode::Segmentop,
    OpCode::Cpoolref,
    OpCode::New,
    OpCode::Insert,
    OpCode::Zpull,
    OpCode::Popcount,
    OpCode::Lzcount,
    OpCode::Spull,
    OpCode::Max,
];

const OPCODE_NAME: [&str; 74] = [
    "BLANK",
    "COPY",
    "LOAD",
    "STORE",
    "BRANCH",
    "CBRANCH",
    "BRANCHIND",
    "CALL",
    "CALLIND",
    "CALLOTHER",
    "RETURN",
    "INT_EQUAL",
    "INT_NOTEQUAL",
    "INT_SLESS",
    "INT_SLESSEQUAL",
    "INT_LESS",
    "INT_LESSEQUAL",
    "INT_ZEXT",
    "INT_SEXT",
    "INT_ADD",
    "INT_SUB",
    "INT_CARRY",
    "INT_SCARRY",
    "INT_SBORROW",
    "INT_2COMP",
    "INT_NEGATE",
    "INT_XOR",
    "INT_AND",
    "INT_OR",
    "INT_LEFT",
    "INT_RIGHT",
    "INT_SRIGHT",
    "INT_MULT",
    "INT_DIV",
    "INT_SDIV",
    "INT_REM",
    "INT_SREM",
    "BOOL_NEGATE",
    "BOOL_XOR",
    "BOOL_AND",
    "BOOL_OR",
    "FLOAT_EQUAL",
    "FLOAT_NOTEQUAL",
    "FLOAT_LESS",
    "FLOAT_LESSEQUAL",
    "UNUSED1",
    "FLOAT_NAN",
    "FLOAT_ADD",
    "FLOAT_DIV",
    "FLOAT_MULT",
    "FLOAT_SUB",
    "FLOAT_NEG",
    "FLOAT_ABS",
    "FLOAT_SQRT",
    "INT2FLOAT",
    "FLOAT2FLOAT",
    "TRUNC",
    "CEIL",
    "FLOOR",
    "ROUND",
    "BUILD",
    "DELAY_SLOT",
    "PIECE",
    "SUBPIECE",
    "CAST",
    "LABEL",
    "CROSSBUILD",
    "SEGMENTOP",
    "CPOOLREF",
    "NEW",
    "INSERT",
    "EXTRACT",
    "POPCOUNT",
    "LZCOUNT",
];

const OPCODE_INDICES: [usize; 74] = [
    0, 39, 37, 40, 38, 4, 6, 60, 7, 8, 9, 64, 5, 57, 1, 68, 66, 61, 71, 55, 52, 47, 48, 41, 43, 44, 49, 46, 51, 42, 53,
    50, 58, 70, 54, 24, 19, 27, 21, 33, 11, 29, 15, 16, 32, 25, 12, 28, 35, 30, 23, 22, 34, 18, 13, 14, 36, 31, 20, 26,
    17, 65, 2, 73, 69, 62, 72, 10, 59, 67, 3, 63, 56, 45,
];

impl OpCode {
    pub fn from_index(value: i64) -> Option<OpCode> {
        if (0..=75).contains(&value) {
            Some(OPCODE_TABLE[value as usize])
        } else {
            None
        }
    }

    pub fn index(self) -> usize {
        self as usize
    }
}

pub fn get_opname(opc: OpCode) -> &'static str {
    OPCODE_NAME.get(opc as usize).copied().unwrap_or("")
}

pub fn get_opcode(nm: &str) -> OpCode {
    let mut min: i32 = 1;
    let mut max: i32 = OpCode::Max as i32 - 1;
    while min <= max {
        let cur = (min + max) / 2;
        let Some(&ind) = OPCODE_INDICES.get(cur as usize) else {
            return OpCode::Blank;
        };
        let candidate = OPCODE_NAME[ind];
        match candidate.as_bytes().cmp(nm.as_bytes()) {
            std::cmp::Ordering::Less => min = cur + 1,
            std::cmp::Ordering::Greater => max = cur - 1,
            std::cmp::Ordering::Equal => return OPCODE_TABLE[ind],
        }
    }
    OpCode::Blank
}

pub fn get_booleanflip(opc: OpCode) -> Option<(OpCode, bool)> {
    match opc {
        OpCode::IntEqual => Some((OpCode::IntNotequal, false)),
        OpCode::IntNotequal => Some((OpCode::IntEqual, false)),
        OpCode::IntSless => Some((OpCode::IntSlessequal, true)),
        OpCode::IntSlessequal => Some((OpCode::IntSless, true)),
        OpCode::IntLess => Some((OpCode::IntLessequal, true)),
        OpCode::IntLessequal => Some((OpCode::IntLess, true)),
        OpCode::BoolNegate => Some((OpCode::Copy, false)),
        OpCode::FloatEqual => Some((OpCode::FloatNotequal, false)),
        OpCode::FloatNotequal => Some((OpCode::FloatEqual, false)),
        OpCode::FloatLess => Some((OpCode::FloatLessequal, true)),
        OpCode::FloatLessequal => Some((OpCode::FloatLess, true)),
        _ => None,
    }
}
